services:
  - type: web
    name: guvenli-portal
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 2 --threads 8 --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /login
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_PATH
        value: /tmp/data.db
      - key: UPLOAD_DIR
        value: /tmp/uploads/messages
      - key: REMEMBER_ME_DAYS
        value: "30"
      - key: DEFAULT_ADMIN_USERNAME
        value: admin
      - key: APP_SECRET_KEY
        sync: false
      - key: DEFAULT_ADMIN_PASSWORD
        sync: false
      - key: DEFAULT_USER_INITIAL_PASSWORD
        sync: false
